branches:
  only: 
    - master
    
language: node_js
node_js:
  - "10"

env:
  - CI=true

install:
  - echo "Skipped"

cache:
  directories:
    - node_modules

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: kendricktan/heiswap-relayer
    bucket: kendrick-codedeploy-artifacts
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kendrick-codedeploy-artifacts
    key: latest.zip
    bundle_type: zip
    application: heiswap-relayer
    deployment_group: heiswap-relayer-deployment-group
    region: us-east-1
    on: *2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip