version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/heiswap-relayer

hooks:
  ApplicationStart:
    - location: codedeploy-scripts/start_relayer.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy-scripts/start_relayer.sh
      timeout: 300
      runas: root