version: '3'
services:
  relayer:
    build: .
    env_file:
      - ./heiswap.env
    expose:
      - "3000"
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'relayer.heiswap.exchange'
      SITES: 'relayer.heiswap.exchange=relayer:3000'

volumes:
  ssl_data: