version: '3'
services:
  relayer:
    build: .
    restart: on-failure
    environment:
      INFURA_PROJECT_ID: ${INFURA_PROJECT_ID}
      ETH_SK: ${ETH_SK}
    expose:
      - "3000"
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'heiswap.exchange'
      SITES: '*.heiswap.exchange=relayer:3000'

volumes:
  ssl_data: